// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#[cfg(feature = "v2_78")]
#[cfg_attr(docsrs, doc(cfg(feature = "v2_78")))]
use crate::ffi;
use glib::translate::*;

#[cfg(feature = "v2_78")]
#[cfg_attr(docsrs, doc(cfg(feature = "v2_78")))]
#[doc(alias = "g_registry_settings_backend_new")]
pub fn registry_settings_backend_new(registry_key: Option<&str>) -> gio::SettingsBackend {
    unsafe {
        from_glib_full(ffi::g_registry_settings_backend_new(
            registry_key.to_glib_none().0,
        ))
    }
}
