// Take a look at the license at the top of the repository in the LICENSE file.

use once_cell::sync::OnceCell;
use std::cell::Cell;
use std::cell::RefCell;
use std::marker::PhantomData;
use std::rc::Rc;
use std::sync::Arc;
use std::sync::Mutex;
use std::sync::RwLock;

use crate::HasParamSpec;

// rustdoc-stripper-ignore-next
/// A type that can be used as a property. It covers every type which have an associated `ParamSpec`
/// (`HasParamSpec`) and some useful types wrapping `HasParamSpec`.
/// The definition is recursive, so you can nest many `Property`s together. The final `ParamSpec` will
/// be the one of the innermost type
pub trait Property {
    type Value;
    type ParamSpec;
}
impl<T: HasParamSpec> Property for T {
    type Value = T;
    type ParamSpec = T::ParamSpec;
}
impl<T: Property> Property for Option<T> {
    type Value = Option<T>;
    type ParamSpec = T::ParamSpec;
}
impl<T: Property> Property for PhantomData<T> {
    type Value = T;
    type ParamSpec = T::ParamSpec;
}
impl<T: Property> Property for RefCell<T> {
    type Value = T;
    type ParamSpec = T::ParamSpec;
}
impl<T: Property> Property for Cell<T> {
    type Value = T;
    type ParamSpec = T::ParamSpec;
}
impl<T: Property> Property for Mutex<T> {
    type Value = T;
    type ParamSpec = T::ParamSpec;
}
impl<T: Property> Property for RwLock<T> {
    type Value = T;
    type ParamSpec = T::ParamSpec;
}
impl<T: Property> Property for OnceCell<T> {
    type Value = T;
    type ParamSpec = T::ParamSpec;
}
// Handle smart pointers trasparently
impl<T: Property> Property for Rc<T> {
    type Value = T::Value;
    type ParamSpec = T::ParamSpec;
}
impl<T: Property> Property for Arc<T> {
    type Value = T::Value;
    type ParamSpec = T::ParamSpec;
}

// rustdoc-stripper-ignore-next
/// A type implementing this trait can be read by the default getter generated by the `Props` macro.
pub trait PropertyRead {
    type Value;
    fn get<R, F: Fn(&Self::Value) -> R>(&self, f: F) -> R;
}

// rustdoc-stripper-ignore-next
/// A type implementing this trait can be written by the default setter generated by the `Props` macro.
pub trait PropertyWrite {
    type Value;
    fn set<F: FnOnce(&mut Self::Value)>(&self, f: F);
}

impl<T> PropertyRead for RefCell<T> {
    type Value = T;
    fn get<R, F: Fn(&Self::Value) -> R>(&self, f: F) -> R {
        f(&self.borrow())
    }
}
impl<T> PropertyWrite for RefCell<T> {
    type Value = T;
    fn set<F: FnOnce(&mut Self::Value)>(&self, f: F) {
        f(&mut self.borrow_mut());
    }
}

impl<T> PropertyRead for Mutex<T> {
    type Value = T;
    fn get<R, F: Fn(&Self::Value) -> R>(&self, f: F) -> R {
        f(&self.lock().unwrap())
    }
}
impl<T> PropertyWrite for Mutex<T> {
    type Value = T;
    fn set<F: FnOnce(&mut Self::Value)>(&self, f: F) {
        f(&mut self.lock().unwrap());
    }
}

impl<T> PropertyRead for RwLock<T> {
    type Value = T;
    fn get<R, F: Fn(&Self::Value) -> R>(&self, f: F) -> R {
        f(&self.read().unwrap())
    }
}
impl<T> PropertyWrite for RwLock<T> {
    type Value = T;
    fn set<F: FnOnce(&mut Self::Value)>(&self, f: F) {
        f(&mut self.write().unwrap());
    }
}

impl<T> PropertyRead for OnceCell<T> {
    type Value = T;
    fn get<R, F: Fn(&Self::Value) -> R>(&self, f: F) -> R {
        f(self.get().unwrap())
    }
}
// This implemenation is a bit of a stretch...
// `ParamStoreWrite` requires a function taking Self::Value, but OnceCell doesn't have
// an internal value before being init. Still, I'm implementing it so that the derive `Props`
// macro can easily work with it
impl<T: Property + Default> PropertyWrite for OnceCell<T> {
    type Value = T;
    fn set<F: FnOnce(&mut Self::Value)>(&self, f: F) {
        let mut v = Self::Value::default();
        f(&mut v);
        // I can't use `unwrap` because I would have to add a `Debug` bound to _v
        if let Err(_v) = self.set(v) {
            panic!("can't set value of OnceCell multiple times")
        };
    }
}

// Smart pointers wrapping a `PropertyRead`/`PropertyWrite`
impl<T: PropertyRead> PropertyRead for Rc<T> {
    type Value = T::Value;
    fn get<R, F: Fn(&Self::Value) -> R>(&self, f: F) -> R {
        (**self).get(f)
    }
}
impl<T: PropertyWrite> PropertyWrite for Rc<T> {
    type Value = T::Value;
    fn set<F: FnOnce(&mut Self::Value)>(&self, f: F) {
        (**self).set(f)
    }
}

impl<T: PropertyRead> PropertyRead for Arc<T> {
    type Value = T::Value;
    fn get<R, F: Fn(&Self::Value) -> R>(&self, f: F) -> R {
        (**self).get(f)
    }
}
impl<T: PropertyWrite> PropertyWrite for Arc<T> {
    type Value = T::Value;
    fn set<F: FnOnce(&mut Self::Value)>(&self, f: F) {
        (**self).set(f)
    }
}
