// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::{prelude::*, translate::*};
use std::fmt;

glib::wrapper! {
    #[doc(alias = "GConverter")]
    pub struct Converter(Interface<ffi::GConverter, ffi::GConverterIface>);

    match fn {
        type_ => || ffi::g_converter_get_type(),
    }
}

impl Converter {
    pub const NONE: Option<&'static Converter> = None;
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::Converter>> Sealed for T {}
}

pub trait ConverterExt: IsA<Converter> + sealed::Sealed + 'static {
    #[doc(alias = "g_converter_reset")]
    fn reset(&self) {
        unsafe {
            ffi::g_converter_reset(self.as_ref().to_glib_none().0);
        }
    }
}

impl<O: IsA<Converter>> ConverterExt for O {}

impl fmt::Display for Converter {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Converter")
    }
}
