// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use std::ffi::CStr;

#[doc(alias = "PANGO_VERSION_STRING")]
pub static VERSION_STRING: once_cell::sync::Lazy<&'static str> =
    once_cell::sync::Lazy::new(|| unsafe {
        CStr::from_ptr(ffi::PANGO_VERSION_STRING).to_str().unwrap()
    });
