// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT
#![allow(deprecated)]

use crate::{Pixbuf, PixbufAnimation, ffi};
use glib::{
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "GdkPixbufSimpleAnim")]
    pub struct PixbufSimpleAnim(Object<ffi::GdkPixbufSimpleAnim, ffi::GdkPixbufSimpleAnimClass>) @extends PixbufAnimation;

    match fn {
        type_ => || ffi::gdk_pixbuf_simple_anim_get_type(),
    }
}

impl PixbufSimpleAnim {
    #[cfg_attr(feature = "v2_44", deprecated = "Since 2.44")]
    #[allow(deprecated)]
    #[doc(alias = "gdk_pixbuf_simple_anim_new")]
    pub fn new(width: i32, height: i32, rate: f32) -> PixbufSimpleAnim {
        unsafe { from_glib_full(ffi::gdk_pixbuf_simple_anim_new(width, height, rate)) }
    }

    #[cfg_attr(feature = "v2_44", deprecated = "Since 2.44")]
    #[allow(deprecated)]
    #[doc(alias = "gdk_pixbuf_simple_anim_add_frame")]
    pub fn add_frame(&self, pixbuf: &Pixbuf) {
        unsafe {
            ffi::gdk_pixbuf_simple_anim_add_frame(self.to_glib_none().0, pixbuf.to_glib_none().0);
        }
    }

    #[cfg_attr(feature = "v2_44", deprecated = "Since 2.44")]
    #[allow(deprecated)]
    #[doc(alias = "gdk_pixbuf_simple_anim_get_loop")]
    #[doc(alias = "get_loop")]
    #[doc(alias = "loop")]
    pub fn is_loop(&self) -> bool {
        unsafe { from_glib(ffi::gdk_pixbuf_simple_anim_get_loop(self.to_glib_none().0)) }
    }

    #[cfg_attr(feature = "v2_44", deprecated = "Since 2.44")]
    #[allow(deprecated)]
    #[doc(alias = "gdk_pixbuf_simple_anim_set_loop")]
    #[doc(alias = "loop")]
    pub fn set_loop(&self, loop_: bool) {
        unsafe {
            ffi::gdk_pixbuf_simple_anim_set_loop(self.to_glib_none().0, loop_.into_glib());
        }
    }

    #[cfg_attr(feature = "v2_44", deprecated = "Since 2.44")]
    #[doc(alias = "loop")]
    pub fn connect_loop_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_loop_trampoline<F: Fn(&PixbufSimpleAnim) + 'static>(
            this: *mut ffi::GdkPixbufSimpleAnim,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::loop".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_loop_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}
